name: random_users
description: Just a static list of Random Users to be used for for all things.
version: 1.0.0
authors: 
- Brady Becker <bradybeck@gmail.com>
- Jeroen Meijer <jeroenfkmeijer@gmail.com>
homepage: http://github.com/bradybeck/random_users

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: ^1.3.3
