name: random_users
version: 0.0.3
description: Just a static list of Random Users to be used for for all things.
author: Brady Becker <bradybeck@gmail.com>
homepage: http://github.com/bradybeck/random_users

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  dart2_constant: ^1.0.0

dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  coverage: ">=0.10.0 <0.13.0"
  dart_dev: ^2.0.0
  dart_style: ^1.0.9
  test: ">=0.12.30 <2.0.0"
